server:
  port: 5000

spring:
  application:
    name: herman
  datasource:
    url: jdbc:postgresql://ep-morning-hall-a1968o7x-pooler.ap-southeast-1.aws.neon.tech/laza?user=nestjs_owner&password=VxW6gRtj4OXb&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html